version: "2.0"

services:
  mongo-db:
    container_name: mongo-db
    image: mongo
    environment: 
      - MONGO_INITDB_DATABASE=teste
  
  mongo-client:
    container_name: mongo-client
    image: mongoclient/mongoclient
    environment: 
      - MONGO_URL=mongodb://mongo-db:27017
    links: 
      - "mongo-db:mongo-client"
    ports: 
      - "3000:3000"