version: "2.0"
volumes:
  vol-mongo:
  vol-nodered:

services:
  mongo-db:
    container_name: mongo-db
    image: mongo
    environment: 
      - MONGO_INITDB_DATABASE=teste
    volumes: 
      - vol-mongo

  mongo-client:
    container_name: mongo-client
    image: mongoclient/mongoclient
    environment: 
      - MONGO_URL=mongodb://mongo-db:27017
    links: 
      - "mongo-db:mongo-client"
    ports: 
      - "3000:3000"

  node-red:
    container_name: node-red
    image: nodered/node-red-docker
    ports:
      - "1880:1880"
    volumes: 
      - vol-nodered

